### ISSUE TITLE
npm install fails due to memwatch-next

### ISSUE THREAD

**Issue by broomstick73** [roman01la/js-memory-usage#5]
npm install fails because of memwatch-next
λ npm install --save memwatch-next

> memwatch-next@0.3.0 install C:\projects\js-memory-usage\node_modules\memwatch-next
> node-gyp rebuild

C:\projects\js-memory-usage\node_modules\memwatch-next>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  heapdiff.cc
  init.cc
  memwatch.cc
  util.cc
  win_delay_load_hook.cc
c:\projects\js-memory-usage\node_modules\memwatch-next\src\heapdiff.cc(95): warning C4996: 'v8::String::Utf8Value::Utf8 Value': was declared deprecated [C:\projects\js-memory-usage\node_modules\memwatch-next\build\memwatch.vcxproj]
  c:\users\jconley\.node-gyp\11.12.0\include\node\v8.h(2991): note: see declaration of 'v8::String::Utf8Value::Utf8Valu
  e'
c:\projects\js-memory-usage\node_modules\memwatch-next\src\init.cc(20): error C2039: 'AddGCEpilogueCallback': is not a
member of 'v8::V8' [C:\projects\js-memory-usage\node_modules\memwatch-next\build\memwatch.vcxproj]

**Comment by roman01la** [comment]
Looks like something is wrong with compiling native addon on your system. Not an issue of this project. Perhaps you should file the issue on memwatch-next repo.
